Added basic gui
Kooldude183/PythonChatClient pull request #1
Opened 2020-11-12 21:09 UTC by AdeelAmad

2020-11-12 21:14 UTC, AdeelAmad commented
Fixed a tiny GUI bug.

2020-11-12 21:16 UTC, AdeelAmad commented
Fixed protocol version

2020-11-13 03:25 UTC, Kooldude183 requested changes
Needs to include features currently present in the existing code

2020-11-13 05:47 UTC, Kooldude183 approved these changes

2020-11-13 05:47 UTC, merged